development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
production:
  adapter: postgresql
  database: apps_meinelog
  pool: 5
  username: meinelog
  password: kzdSv7&kFC~b_njZ
  host: localhost
  timeout: 5000